spring.application.name=crud
vaadin.launch-browser=true

spring.datasource.url=jdbc:postgresql://localhost:5432/crud_db
spring.datasource.username=crud_user
spring.datasource.password=crud_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true